version: "3.8"
services:
  backend:
    image: "floredenis2001/online-school-app:26.8.2023.7.6.50"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev